//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HotelGuests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelGuests()
        {
            this.GuestPassports = new HashSet<GuestPassports>();
            this.GuestsPhoneNumbers = new HashSet<GuestsPhoneNumbers>();
            this.HotelsRoomRegistration = new HashSet<HotelsRoomRegistration>();
            this.OrdersRegistration = new HashSet<OrdersRegistration>();
        }

        [Required(ErrorMessage = "This field can't be empty")]
        [StringLength(60, MinimumLength = 6, ErrorMessage = "Login is not valid")]
        [Display(Name = "Login")]
        public string GuestMail { get; set; }
        [Required(ErrorMessage = "This field can't be empty")]
        [StringLength(40, MinimumLength = 1)]
        public string Surname { get; set; }
        [Required(ErrorMessage = "This field can't be empty")]
        [StringLength(40, MinimumLength = 1)]
        public string Name { get; set; }
        public string Patronymic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestPassports> GuestPassports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestsPhoneNumbers> GuestsPhoneNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelsRoomRegistration> HotelsRoomRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersRegistration> OrdersRegistration { get; set; }
    }
}
